### ISSUE TITLE
[TASK] Create release for 2.0.0

### ISSUE THREAD

**Issue by machwatt** [machwatt/sf_filecollection_gallery#64]

**Comment by StanislavSeifert** [comment]
Hi Jöran, 
what do you think when you will relase Tag 2.0.0. Thank you!
Stan

**Comment by machwatt** [comment]
Good question.., unfortunately i don't have much time currently to work on this extension 👎

**Comment by derhansen** [comment]
New version 1.3.0 has been released on TER
