### ISSUE TITLE
[TASK] Add foldername to ListFromFolderAction

### ISSUE THREAD

**Issue by machwatt** [machwatt/sf_filecollection_gallery#65]

**Comment by Patta** [comment]
Any plans to release this important task ? Thanks

**Comment by Patta** [comment]
Also we need the {galleryTitle} on top of the list (List.html) if display mode is nested (Nested.html).

**Comment by Patta** [comment]
[PR](https://github.com/machwatt/sf_filecollection_gallery/pull/86)
