### ISSUE TITLE
Template changing is not working

### ISSUE THREAD

**Issue by tauchvogel** [machwatt/sf_filecollection_gallery#72]
I am using Typo3 6.2.25 and the newest extension of filecollectiongallery. I put the Templates into an own directory into fileadmin and I changed the settings to it. (Like to see in the documentation!)

In the pagination template I changed the ul class to "pagination". But the changing will not work. It seems, that something is not loaded correctly. I don 't know what to do. Do you need any sourcecode?

**Comment by machwatt** [comment]
Seems like you are right and its not possible to change the pagination widgets' template. Did you manage to change the other templates?

**Comment by tauchvogel** [comment]
Is it right that the changing of the path of the theme is made with this: 

> plugin.tx_sffilecollectiongallery {
    view.templateRootPaths.1 = fileadmin/templates/ext/gallery/Resources/Private/Templates/
}

It will be in the Setup field of the root template?

If yes, nothing happens to the changing of the theme.

**Comment by tauchvogel** [comment]
When I change the original template in the typo3conf/ext/sf_filecollection_gallery/ directory, then it changes the e.g. pagination. But not in the copy in fileadmin. What is wrong?

**Comment by tauchvogel** [comment]
In Fileadmin I can change only the gallery template. In typo3conf I can change the pagination. How can I do it all in fileadmin? And how can I enable a lightbox?

**Comment by tauchvogel** [comment]
I do not want close the topic!
