### ISSUE TITLE
No a tag of Fluid template loaded

### ISSUE THREAD

**Issue by tauchvogel** [machwatt/sf_filecollection_gallery#75]
I am using Typo3 6.2.14 on a online shared hosting server. The gallery list-template is nor loaded correctly. There are no a tags around the listed images.

In the nested template the file works fine and correct.

What could it be?

The homepage is not an public page, so I can not publish a link here!

**Comment by machwatt** [comment]
Hey tauchvogel. I am on a vacation until monday. You might mail me directly so we get your issue out of public while we discover your bugs.

**Comment by tauchvogel** [comment]
Today I maybe found this "bug". I have not activated the button "Enable lightbox". After this the link is working.

But if anybody is not working with a lightbox, how can he activate the links?
