### ISSUE TITLE
Error with TYPO3 8.6

### ISSUE THREAD

**Issue by Hobokens** [machwatt/sf_filecollection_gallery#77]
Hi,

i'm just testing the new LTS. With sf_filecollection_gallery I get the following error on my local machine:

`Call to undefined method TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getPageRenderer() 
Error thrown in file
W:\xxxx\htdocs\xxxx\typo3conf\ext\sf_filecollection_gallery\Classes\ViewHelpers\IncludeFileViewHelper.php in line 49.`

Do you plan to update this nice extension?

Regards
Hobokens

**Comment by machwatt** [comment]
Yep, but i dont know if i get it ready until the official launch of 8LTS. But i'll have a look into it. Thanks for reporting this error.

**Comment by Hobokens** [comment]
This problem is easy to solve.
Just copy the [IncludeFileViewHelper](https://github.com/georgringer/news/blob/master/Classes/ViewHelpers/IncludeFileViewHelper.php)
from Georg Ringers Extension 'news'.

Regards
Hobokens

**Comment by Patta** [comment]
@Hobokens,  after replacing of the IncludeFileViewHelper with the viewhelper from EXT:news i get this exception error: 
Uncaught TYPO3 Exception
#1460976233: You must either specify a string src or a File object. 

I think there are other things to do for v8 LTS.

**Comment by Patta** [comment]
fixed with PR #80

**Comment by derhansen** [comment]
Closing issue
