### ISSUE TITLE
2 Features Requests

### ISSUE THREAD

**Issue by Hobokens** [machwatt/sf_filecollection_gallery#78]
Hi,
1) Using the nested view with file collection (NestedFromFolder.html) it would be nice to have the titles of the filecollections as {object.galleryFolderName}.

2) It would be nice to have the title of the shown folder/file collection on top of the template 'ListFromFolder.html' 

Regards
Hobokens

**Comment by derhansen** [comment]
Both should not be possible with #86

**Comment by Hobokens** [comment]
Thanks a lot.
