### ISSUE TITLE
TYPO3 9 compatibility

### ISSUE THREAD

**Issue by msollmann** [machwatt/sf_filecollection_gallery#90]
Are you planning a version for TYPO3 9? Would be great!

**Comment by derhansen** [comment]
Yes, @machwatt is working on a version for TYPO3 9

**Comment by msollmann** [comment]
Do you know when the extension will be ready, approximately?

**Comment by machwatt** [comment]
I starting working on it today and hopefully find the time to finish it this week.

**Comment by machwatt** [comment]
@msollmann So i filed a release 1.5.0 with support for v9 – should work as intented. 
The pagination template has changed a little. 

Releasing to TER later on.

**Comment by msollmann** [comment]
Yes, it works! Thank you very much!

**Comment by Patta** [comment]
There are some problems in my environment:
- the css file is not included
- the paginator is displayed even if there is only one page, previously it was hidden (templates are adopted like in 2c4874c)
- the paginator does not accept the markup from template/paginate/index.html

**Comment by machwatt** [comment]
I consider this as closed now – thanks for your support there Patta.
