### ISSUE TITLE
Packagist registration missing

### ISSUE THREAD

**Issue by garbast** [machwatt/sf_filecollection_gallery#96]
Please consider to register this extension at packagist. This would take away the necessity to register the repository in composer.json.

**Comment by RobertKesseler** [comment]
Yes please. 
Or is this plugin abandoned?

**Comment by machwatt** [comment]
https://packagist.org/packages/machwatt/sf_filecollection_gallery should work now.

**Comment by RobertKesseler** [comment]
Works for me. Thank you!

**Comment by machwatt** [comment]
Perfect
